routingRules:
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "http://59.144.184.105:8087/api/bpp/webhook"
    endpoints:
      - on_discover
      - on_select
      - on_init
      - on_confirm
      - on_status
      - on_update
      - on_cancel
      - on_track
      - on_rate
      - on_support
