routingRules:
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "http://59.144.184.105:8087/api/bpp/webhook"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rate
      - support